
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
server:
  servlet:
    context-path: /sell
wochat:
  mpAppId: wx6ad144e54af67d87
  mpAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
wechat:
  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: C:\Users\ZJM\Downloads\spring-boot-samples-master\spring-boot-samples-master\sell\h5.p12
  notifyUrl: http://entry.nat300.top/sell/pay/notify