spring:
  datasource:
    url: jdbc:mysql://192.168.56.191/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true